/*{
Akontb :this.      
Anreda :this.      
Bankld :this.      
Banknd :this.      
Banksd :this.     
Bkontd :this.    
Bkrefd :this.     
Brscha :this.     
Bukrsb :this.    
Bvtypd :this.    
Ekgrpc :this.      
Ekorgc :this.   
Emnfra :this.   
Fdgrvb :this.     
Fitypa :this.     
Frgrpb :this.     
Intadb :this.     
Koinhd :this.     
Ktokka :this.    
Land1a :this.    
Lzonea :this.     
Meprfc :this.     
Name1a :this.     
Name2a :this.     
Name3a :this.     
Name4a :this.     
Ort01a :this.     
Ort02a :this.      
Pfacha :this.      
Pforta :this.      
Pstl2a :this.      
Pstlza :this.      
Qssysa :this.      
Regioa :this.     
Scacda :this.      
Sortla :this.      
Sprasa :this.      
Stcd3a :this.      
Stcd4a :this.      
Stcdta :this.      
Stenra :this.      
Strasa :this.      
Telbxa :this.      
Telf1a :this.      
Telf2a :this.      
Teltxa :this.      
Telx1a :this.      
Tlfnsb :this.      
Tlfxsb :this.      
Txjcda :this.      
Waersc :this.     
Ztermb :this.      
Zwelsb :this.      
}*/